name: Auto-respond to PRs

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Comment on PR
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          🚀 **Thanks for your PR!** 🎓
          I'm currently preparing for exams and won't be able to review pull requests until **March 10, 2025**.
          You have been put in a review queue. ✅
